// src/pages/SmileGallery/smileGallery.styles.js

const styles = {
  section: {
    position: 'relative',
    py: { xs: 5, md: 8 },
    minHeight: '70vh',
    background:
      'linear-gradient(180deg, #f4fbfb 0%, #ffffff 45%, #f7fcfc 100%)',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '-120px',
      right: '-120px',
      width: '420px',
      height: '420px',
      borderRadius: '50%',
      background:
        'radial-gradient(circle, rgba(13,177,173,0.18) 0%, transparent 70%)',
      pointerEvents: 'none',
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: '-140px',
      left: '-100px',
      width: '380px',
      height: '380px',
      borderRadius: '50%',
      background:
        'radial-gradient(circle, rgba(255,123,107,0.14) 0%, transparent 70%)',
      pointerEvents: 'none',
    },
  },
  eyebrow: {
    display: 'inline-block',
    fontSize: '0.75rem',
    fontWeight: 700,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: '#088a87',
    background: '#e6faf9',
    px: 2,
    py: 0.75,
    borderRadius: 999,
    mb: 2,
  },
  heading: {
    mb: 2,
    fontWeight: 800,
    fontSize: { xs: '2rem', md: '2.75rem' },
    letterSpacing: '-0.02em',
    color: '#0f2a2a',
    textAlign: 'center',
    background: 'linear-gradient(90deg, #088a87, #0db1ad)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  subheading: {
    textAlign: 'center',
    color: '#5a6b6b',
    maxWidth: 640,
    mx: 'auto',
    mb: { xs: 4, md: 6 },
    fontSize: { xs: '0.98rem', md: '1.1rem' },
    lineHeight: 1.65,
  },
  headerWrap: {
    textAlign: 'center',
    position: 'relative',
    zIndex: 1,
  },
  loading: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    justifyContent: 'center',
    mt: 8,
    mb: 8,
    color: '#088a87',
  },
  errorBox: {
    maxWidth: 640,
    mx: 'auto',
    mb: 4,
    borderRadius: 3,
    boxShadow: '0 4px 14px rgba(211, 47, 47, 0.12)',
  },
  emptyState: {
    textAlign: 'center',
    py: 8,
    px: 3,
    maxWidth: 480,
    mx: 'auto',
    borderRadius: 4,
    background: 'rgba(255,255,255,0.7)',
    backdropFilter: 'blur(8px)',
    border: '1px dashed rgba(13, 177, 173, 0.3)',
  },
  emptyIcon: {
    fontSize: '3rem',
    mb: 2,
    opacity: 0.6,
  },
};

export default styles;
